### PR TITLE
feat(nodes): make it possible to set origin per node

### PR DESCRIPTION
**Pull request by ekiwi111**
Discussion - https://github.com/wbkd/react-flow/discussions/2871

### CODE REVIEW

**Comment by bcakmakoglu** [comment]
This PR doesn't cover store actions like 
1. `setNodes`
2. `setDefaultNodesAndEdges`
3. `updateNodeDimensions`
4. `triggerNodeChanges`

There's probably a couple more places where `nodeOrigin` would have to be updated to use either the per node origin or the global nodeOrigin.

**Comment by e-oldman** [comment]
> This PR doesn't cover store actions like
> 
> 1. `setNodes`
> 2. `setDefaultNodesAndEdges`
> 3. `updateNodeDimensions`
> 4. `triggerNodeChanges`
> 
> There's probably a couple more places where `nodeOrigin` would have to be updated to use either the per node origin or the global nodeOrigin.

Thanks for the directions, will look into that

**Comment by moklick** [comment]
This will be possible with the next major or eventually minor release. It's already implemented in the "feat/packages" branch.

**Comment by moklick** [comment]
This is part of the v12 release. It's still in beta, but you can already try it out. All details: https://github.com/xyflow/xyflow/discussions/3764

**Pull request closed without merging**
