### PR TITLE
feat: accept any `path` element attribute as a prop

### PR DESCRIPTION
**Pull request by mhuggins**
This is an attempt to implement a solution for #4821.

Unfortunately, I could not seem to get my development environment set up following the contributing instructions.  After running `pnpm install`, I was still seeing lint/typecheck errors before even beginning to make changes.

### CODE REVIEW

**Comment by peterkogo** [comment]
@mhuggins Thanks for the initial PR! I saw that we can simplify a couple of things here and there.

I tried passing `pathLength` to the `<BaseEdge />` which now works but Typescript is complaining. 

I don't understand why even this is throwing a Typescript error:
```ts
const x : React.HTMLAttributes<SVGPathElement> = { pathLength: 5 };
```

Do you have any idea?

**Comment by mhuggins** [comment]
@peterkogo I fixed this by changing `HTMLAttributes<...>` to `SVGAttributes<...>` for the typing.  I realized there were a couple other places that appeared to use this generic type incorrectly, so I updated those too.

I also added an example that demonstrates the `pathLength` being used in conjunction with a CSS animation that leverages the known path length.

**Comment by moklick** [comment]
Thanks for your help @mhuggins! I like the idea to pass svg attrs to the `BaseEdge` component but I am not sure if I would do the same for all built in edges. As soon as you want to do something fancy, you should use the `BaseEdge` and build your own edge component I would say. This would also make this change smaller since we would only need to update the `BaseEdge` component and not care about the prop drilling of the built in edges. wdyt?

**Comment by peterkogo** [comment]
I removed quite a lot of manual prop drilling from some of the components. Some, like the straight edge, were using `...props` already. 

In reverse this means we have to prop drill for all components manually. Either way is fine for me.

**Comment by moklick** [comment]
The prop drilling was introduced with this PR I think. Current main: https://github.com/xyflow/xyflow/blob/main/packages/react/src/components/Edges/StraightEdge.tsx

**Comment by peterkogo** [comment]
You're right! I must have mistaken the StepEdge for a regular Edge. Will revert it.

**Comment by peterkogo** [comment]
@moklick done, it's better this way.

**Comment by mhuggins** [comment]
Thanks for helping see this through, everyone! 😄

**Pull request merged**
